config/routes.rb
Robotics::Application.routes.draw do
  resources :pages, :only => [:index, :show] do
    get "home", :on => :collection
  end

  resources :menus,  :only => [:show]
  resources :albums, :only => [:index, :show]
  resources :photos, :only => [:show]
  resources :feedbacks, :only => [:create]

  get "sitemap" => "pages#index", :as => :sitemap

  root :to => "pages#home"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  validates_presence_of :title, :external_url, :image, :format

  scope :rotating_sidebar, where(:format => "rotating", :active => true).order("priority DESC")
  scope :dashboard, where(:active => true).order("updated_at DESC").limit(15).group(:format)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :location_datas
  has_many :photos
  has_many :locations, :through => :location_datas
  accepts_nested_attributes_for :location_datas

  default_scope order("updated_at DESC")

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  def first_image
    if self.photos.length > 0
      self.photos.first.thumb
    else
      "/no-thumbnail.jpg"
    end
  end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  def self.person_categories
    ["Interested Student", "FIRST Student", "FIRST Mentor", "Past FIRST Participant", "Parent", "Sponsor", "Other"]
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :album
  belongs_to :photo
  geocoded_by :place
  after_validation :geocode, :if => :place_changed?

  # For Formtastic collections.
  def name
    self.place
  end
end

app/models/location_data.rb
class LocationData < ActiveRecord::Base
  belongs_to :album
  belongs_to :photo
  belongs_to :location
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  validates_uniqueness_of :title
  has_many :pages

  scope :ordered, order("priority DESC, title")
  scope :alphabetical, order("title")

  def items
    self.pages.reorder("title")
  end

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  before_save :change_index, :if => :is_index?
  belongs_to :menu
  validate :external_link_only, :if => :external_link?

  default_scope order("updated_at DESC")
  scope :pages_with_content, where("content IS NOT NULL and content != ''")
  scope :pages_with_external, where("external_link IS NOT NULL and external_link != ''")

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  def self.home
    Page.find_by_is_index(true)
  end

  private

  def change_index
    p = Page.home
    p.update_attribute(:is_index, false) if p
  end

  def external_link_only
    if self.content?
      errors.add(:content, "not allowed if an external URL is specified.")
    end
  end
end

app/models/photo.rb
require "fileutils"

class Photo < ActiveRecord::Base
  belongs_to :album
  has_many :location_datas
  has_many :locations, :through => :location_datas
  accepts_nested_attributes_for :location_datas

  has_attached_file :image
  has_attached_file :thumbnail

  validates_attachment_presence :image, :if => Proc.new { |i| i.image_file_name_changed? or i.new_record? }

  default_scope order("updated_at DESC")

  def next
    photo = Photo.unscoped.where(:album_id => self.album_id).where("updated_at > ?", self.updated_at).limit(1).first
    photo = Photo.unscoped.order("updated_at").limit(1).first if photo.nil?
    photo
  end

  def prev
    photo = Photo.where(:album_id => self.album_id).where("updated_at < ?", self.updated_at).limit(1).first
    photo = Photo.limit(1).first if photo.nil?
    photo
  end

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  def thumb
    if self.thumbnail_file_name.present?
      self.thumbnail.url
    else
      self.image.url
    end
  end
end

app/models/posting.rb
require "net/http"
require "uri"

class Posting < ActiveRecord::Base
  validates_length_of :content, :maximum => 140

  scope :board, order("sticky DESC, max(custom_date, created_at)").limit(5)
  scope :news, where(:category => "News").board
  scope :events, where(:category => "Events").board
  scope :team_notices, where(:category => "Team Notices").board

  def date
    d = self.custom_date.nil? ? created_at.to_date : custom_date.to_date
    buf = d.to_formatted_s(:long)
    buf += " - " + self.end_date.to_date.to_formatted_s(:long) if self.end_date.present?
    buf
  end

  def self.categories
    ["News", "Events", "Team Notices"]
  end

  def self.pull_from_gcalendar!
    url = "http://www.google.com/calendar/feeds/#{Robotics::Application.config.calendar_email}/public/full?v=2"
    data = Hash.from_xml(Net::HTTP.get(URI.parse(url)))
    data["feed"]["entry"].each do |entry|
      # Validate entry
      next unless entry["when"]["startTime"].to_datetime >= DateTime.yesterday
      next unless entry["title"][0] == "*"

      post = Posting.find_by_gcalendar_id(entry["id"])
      post = Posting.new unless post
      post.content = entry["title"][1..-1].strip
      post.custom_date = entry["when"]["startTime"].to_datetime
      post.end_date = entry["when"]["endTime"].to_datetime unless entry["when"]["startTime"].to_date + 1.day == entry["when"]["endTime"].to_date
      post.category = "Team Notices"
      post.gcalendar_id = entry["id"]
      post.save
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id].to_i)
  end

  def index
    @albums = Album.all
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def show
    @menu = Menu.find(params[:id].to_i)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    respond_to do |f|
      f.html
      f.xml
    end
  end

  def show
    @page = Page.find(params[:id].to_i)
    render_printer_capable
  end

  def home
    @page = Page.find_by_is_index(true)
    render_printer_capable
  end

  private

  def render_printer_capable
    if params[:print].present?
      render :show, :layout => "print"
    else
      render :show
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  respond_to :js

  def show
    @photo = Photo.find(params[:id].to_i)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(str)
    main = Robotics::Application.config.page_title
    str.blank? ? main : "#{str} | #{main}"
  end

  def m(str)
    return "" if str.blank?
    RDiscount.new(str, :smart, :autolink).to_html.html_safe
  end

  def sub_menu_link(page)
    if page.external_link.blank?
      link_to page.title, page_path(page)
    else
      options = {}
      options[:target] = "_blank" unless page.external_link[0] == "/"
      link_to page.title, page.external_link, options
    end
  end

  def query(hash)
    request.query_string.split("&").inject({}) { |hash, pair|
      key, value = pair.split("=")
      hash.merge(key.to_sym => value)
    }.merge(hash).inject("?") { |str, pair| str + "#{pair[0].to_s}=#{pair[1]}&" }[0..-2]
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/admin/dashboard/_ads.html.erb
<table id="ads-dashboard">
  <% Ad.dashboard.each do |ad| %>
    <tr>
      <td class="image">
        <%= image_tag(ad.image, :width => "60") %>
      </td>
      <td>
        <%= link_to ad.title, ad.external_url, :target => "_blank" %><br />
        [<%= ad.format.capitalize %>]<br />
        <%= link_to "Quick Edit", edit_admin_ad_path(ad) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/dashboard/_content_pages.html.erb
<ul id="content-pages-dashboard">
  <% Page.pages_with_content.each do |page| %>
    <li><%= link_to page.title, page_path(page), :target => "_blank" %> [<%= link_to "Edit", edit_admin_page_path(page) %>]</li>
  <% end %>
</ul>

app/views/admin/dashboard/_external_pages.html.erb
<ul id="external-pages-dashboard">
  <% Page.pages_with_external.each do |page| %>
    <li><%= link_to page.title, page.external_link, :target => "_blank" %> [<%= link_to "Edit", edit_admin_page_path(page) %>]</li>
  <% end %>
</ul>

app/views/admin/dashboard/_links.html.erb
<ul id="menu-dashboard">
  <% Menu.ordered.each do |menu| %>
    <li><%= link_to menu.title, menu_path(menu) %> [<%= link_to "Edit", edit_admin_menu_path(menu) %>]</li>
  <% end %>
</ul>
<%= link_to "New Menu Heading", new_admin_menu_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title content_for(:title) %></title>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="keywords" content="first, robots, robotics competition, frc, mmrambotics, rambotics, mmrobinson, hdsb, competition, 2200, ontario" />
  <meta name="description" content="MMRambotics is a team of students from M.M. Robinson High School who build robots to compete in the FIRST Robotics Competition." />
  <meta name="author" content="MMRambotics FRC 2200" />

  <%= stylesheet_link_tag "application" %>

  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <div id="lightbox">
    <div id="lightbox-header"><%= image_tag "lightbox-close.png" %></div>
    <div id="lightbox-alternate-close"><span>Close</span></div>
    <div id="lightbox-content"></div>
  </div>

  <div id="bar">
    News, Events, Notices
  </div>
  <div id="slide-down">
    <section>
    <div id="postings">
      <%= render :partial => "postings/three_column", :locals => { :news => @news, :events => @events, :team_notices => @team_notices } %>
    </div>
    </section>
  </div>

  <div id="container">
    <div id="main-container">
      <div id="sidebar">
        <aside>
        <div id="non-twitter">
          <%= render :partial => "menus/menu" %>
          <%= render :partial => "ads/rotating" %>
        </div>
        <%= render :partial => "menus/twitter" %>
        </aside>
      </div>

      <div id="content">
        <div id="header">
          <header>
          <h2><%= content_for :title %></h2>
          <h3><%= Robotics::Application.config.page_subheading %></h3>
          </header>
        </div>
        <div id="page-content">
          <article>
          <%= yield %>
          </article>
        </div>
      </div>
    </div>
  </div>

  <div id="feedback-button">
    <span><%= link_to "Feedback", query(:feedback => true), :id => "feedback-anchor" %></span>
  </div>

  <div id="feedback-form" <%= params[:feedback] == "true" ? "" : "class='hidden'" %>>
    <%= render :partial => "feedback/new" %>
  </div>

  <%= render :partial => "pages/analytics" %>
</body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title content_for(:title) %></title>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Petrona' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "readability" %>
  <%= stylesheet_link_tag "printer", :media => "print" %>
</head>

<body class="<%= params[:colour] %>">
  <div id="print-container" class="<%= params[:font] || "f1" %>">
    <div id="controls">
      <div id="colour-themes">
        <%= link_to " ", query(:colour => ""), :id => "white-theme" %>
        <%= link_to " ", query(:colour => "black"), :id => "black-theme" %>
      </div>
      <div style="clear: both;"></div>
      <div id="font-themes">
        <%= link_to "a", query(:font => "f1"), :class => "f1" %>
        <%= link_to "a", query(:font => "f2"), :class => "f2" %>
        <%= link_to "a", query(:font => "f3"), :class => "f3" %>
        <%= link_to "a", query(:font => "f4"), :class => "f4" %>
      </div>
      <div style="clear: both;"></div>
    </div>
    <div id="content">
      <h2><%= content_for(:title) %></h2>
      <%= yield %>
    </div>
  </div>

  <%= render :partial => "pages/analytics" %>
</body>
</html>

app/views/pages/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-20014228-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/pages/_page_meta.html.erb
<aside>
<div id="page-meta">
  <%= link_to "Printer/Reader Friendly", query(:print => "friendly") %>
  | <%= link_to "Back to Top", "#" %>
</div>
</aside>

app/views/pages/_social.html.erb
<aside>
<!-- ShareThis -->
<div id="share-this-container">
  <h4 id="share-this-header">Share This</h4>
  <div><span  class='st_sharethis_large' ></span><span  class='st_email_large' ></span><span  class='st_twitter_large' ></span><span  class='st_facebook_large' ></span><span  class='st_instapaper_large' ></span><span  class='st_linkedin_large' ></span><span  class='st_google_reader_large' ></span><span  class='st_reddit_large' ></span><span  class='st_stumbleupon_large' ></span><span  class='st_tumblr_large' ></span><span  class='st_plusone_large' ></span></div>
  <script type="text/javascript">var switchTo5x=true;</script><script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script><script type="text/javascript">stLight.options({publisher:'133ec31c-b674-4f92-b834-81d9b3e66560'});</script>
</div>
</aside>

app/views/pages/index.html.erb
<%= content_for :title, "Site Map" %>

<%= link_to "Sitemap XML", sitemap_path(:xml) %>

<ul id="site-map-menu">
  <li><%= link_to "Home", Page.home %></li>
  <% Menu.alphabetical.each do |menu| %>
    <% @menu = menu %>
    <%= render :partial => "menus/individual" %>
  <% end %>
</ul>

app/views/pages/show.html.erb
<%= content_for :title, @page.title %>

<%=m @page.content %>

<%= render :partial => "social" %>
<%= render :partial => "page_meta" %>