config/routes.rb
Robotics::Application.routes.draw do
  resources :pages, :only => [:index, :show] do
    get "home", :on => :collection
  end

  resources :menus,  :only => [:show]
  resources :albums, :only => [:index, :show]
  resources :photos, :only => [:show]
  resources :feedbacks, :only => [:create]

  get "sitemap" => "pages#index", :as => :sitemap

  root :to => "pages#home"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  validates_presence_of :title, :external_url, :image, :format

  scope :rotating_sidebar, where(:format => "rotating", :active => true).order("priority DESC")
  scope :dashboard, where(:active => true).order("updated_at DESC").limit(15).group(:format)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :location_datas
  has_many :photos
  has_many :locations, :through => :location_datas
  accepts_nested_attributes_for :location_datas

  default_scope order("updated_at DESC")

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  def first_image
    if self.photos.length > 0
      self.photos.first.thumb
    else
      "/no-thumbnail.jpg"
    end
  end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  def self.person_categories
    ["Interested Student", "FIRST Student", "FIRST Mentor", "Past FIRST Participant", "Parent", "Sponsor", "Other"]
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :album
  belongs_to :photo
  geocoded_by :place
  after_validation :geocode, :if => :place_changed?

  # For Formtastic collections.
  def name
    self.place
  end
end

app/models/location_data.rb
class LocationData < ActiveRecord::Base
  belongs_to :album
  belongs_to :photo
  belongs_to :location
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  validates_uniqueness_of :title
  has_many :pages

  scope :ordered, order("priority DESC, title")
  scope :alphabetical, order("title")

  def items
    self.pages.reorder("title")
  end

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  before_save :change_index, :if => :is_index?
  belongs_to :menu
  validate :external_link_only, :if => :external_link?

  default_scope order("updated_at DESC")
  scope :pages_with_content, where("content IS NOT NULL and content != ''")
  scope :pages_with_external, where("external_link IS NOT NULL and external_link != ''")

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  def self.home
    Page.find_by_is_index(true)
  end

  private

  def change_index
    p = Page.home
    p.update_attribute(:is_index, false) if p
  end

  def external_link_only
    if self.content?
      errors.add(:content, "not allowed if an external URL is specified.")
    end
  end
end

app/models/photo.rb
require "fileutils"

class Photo < ActiveRecord::Base
  belongs_to :album
  has_many :location_datas
  has_many :locations, :through => :location_datas
  accepts_nested_attributes_for :location_datas

  has_attached_file :image
  has_attached_file :thumbnail

  validates_attachment_presence :image, :if => Proc.new { |i| i.image_file_name_changed? or i.new_record? }

  default_scope order("updated_at DESC")

  def next
    photo = Photo.unscoped.where(:album_id => self.album_id).where("updated_at > ?", self.updated_at).limit(1).first
    photo = Photo.unscoped.order("updated_at").limit(1).first if photo.nil?
    photo
  end

  def prev
    photo = Photo.where(:album_id => self.album_id).where("updated_at < ?", self.updated_at).limit(1).first
    photo = Photo.limit(1).first if photo.nil?
    photo
  end

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  def thumb
    if self.thumbnail_file_name.present?
      self.thumbnail.url
    else
      self.image.url
    end
  end
end

app/models/posting.rb
require "net/http"
require "uri"

class Posting < ActiveRecord::Base
  validates_length_of :content, :maximum => 140

  scope :board, order("sticky DESC, max(custom_date, created_at)").limit(5)
  scope :news, where(:category => "News").board
  scope :events, where(:category => "Events").board
  scope :team_notices, where(:category => "Team Notices").board

  def date
    d = self.custom_date.nil? ? created_at.to_date : custom_date.to_date
    buf = d.to_formatted_s(:long)
    buf += " - " + self.end_date.to_date.to_formatted_s(:long) if self.end_date.present?
    buf
  end

  def self.categories
    ["News", "Events", "Team Notices"]
  end

  def self.pull_from_gcalendar!
    url = "http://www.google.com/calendar/feeds/#{Robotics::Application.config.calendar_email}/public/full?v=2"
    data = Hash.from_xml(Net::HTTP.get(URI.parse(url)))
    data["feed"]["entry"].each do |entry|
      # Validate entry
      next unless entry["when"]["startTime"].to_datetime >= DateTime.yesterday
      next unless entry["title"][0] == "*"

      post = Posting.find_by_gcalendar_id(entry["id"])
      post = Posting.new unless post
      post.content = entry["title"][1..-1].strip
      post.custom_date = entry["when"]["startTime"].to_datetime
      post.end_date = entry["when"]["endTime"].to_datetime unless entry["when"]["startTime"].to_date + 1.day == entry["when"]["endTime"].to_date
      post.category = "Team Notices"
      post.gcalendar_id = entry["id"]
      post.save
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id].to_i)
  end

  def index
    @albums = Album.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :get_postings
  before_filter :new_feedback

  def get_postings
    @news = Posting.news
    @events = Posting.events
    @team_notices = Posting.team_notices
  end

  def new_feedback
    @new_feedback = Feedback.new
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def create
    Feedback.new(params[:feedback].merge({:ip => request.remote_ip})).save
    redirect_to root_path
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def show
    @menu = Menu.find(params[:id].to_i)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    respond_to do |f|
      f.html
      f.xml
    end
  end

  def show
    @page = Page.find(params[:id].to_i)
    render_printer_capable
  end

  def home
    @page = Page.find_by_is_index(true)
    render_printer_capable
  end

  private

  def render_printer_capable
    if params[:print].present?
      render :show, :layout => "print"
    else
      render :show
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  respond_to :js

  def show
    @photo = Photo.find(params[:id].to_i)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(str)
    main = Robotics::Application.config.page_title
    str.blank? ? main : "#{str} | #{main}"
  end

  def m(str)
    return "" if str.blank?
    RDiscount.new(str, :smart, :autolink).to_html.html_safe
  end

  def sub_menu_link(page)
    if page.external_link.blank?
      link_to page.title, page_path(page)
    else
      options = {}
      options[:target] = "_blank" unless page.external_link[0] == "/"
      link_to page.title, page.external_link, options
    end
  end

  def query(hash)
    request.query_string.split("&").inject({}) { |hash, pair|
      key, value = pair.split("=")
      hash.merge(key.to_sym => value)
    }.merge(hash).inject("?") { |str, pair| str + "#{pair[0].to_s}=#{pair[1]}&" }[0..-2]
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/index.html.erb
<% content_for :title, "All Albums" %>

<div id="albums-header">
  <span id="album-header-info"></span>
  <span><%= link_to "Thumbnails", query(:view => :thumb), :class => "small-button", :id => "albums-thumb-button" %></span>
  <span><%= link_to "List",       query(:view => :list),  :class => "small-button", :id => "albums-list-button" %></span>
</div>

<div id="albums-container">
  <div id="albums-thumbnails"<%= params[:view] == "thumb" ? "" : "style='display:none;'" %>>
    <% @albums.each do |album| %>
      <% if album.photos.length > 0 %>
        <div class="image">
          <%= link_to image_tag(album.first_image, :size => "150x150"), album_path(album), :title => album.title %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div id="albums-listing"<%= params[:view] == "thumb" ? "style='display:none';" : "" %>>
    <table>
      <tbody>
        <% @albums.each do |album| %>
          <% if album.photos.length > 0 %>
            <tr>
              <td><%= link_to image_tag(album.first_image, :size => "100x100"), album_path(album), :title => album.title %></td>
              <td>
                <div class="album-short">
                  <b><div><%= album.title %></div></b><br />
                  Updated <%= time_ago_in_words(album.updated_at) %> ago.<br />
                  <%= pluralize(album.photos.length, "Photo") %>
                  <% if album.read_more.present? %>
                    <br /><%= link_to "Read More", album.read_more %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="left-offset"><%= render :partial => "pages/social" %></div>

app/views/albums/show.html.erb
<% content_for :title, @album.title %>

<div id="albums-header">
  <span id="album-header-info"></span>
  <span><%= link_to "Thumbnails", query(:view => :thumb), :class => "small-button", :id => "albums-thumb-button" %></span>
  <span><%= link_to "List",       query(:view => :list),  :class => "small-button", :id => "albums-list-button" %></span>
  <span><%= link_to "Other Albums", albums_path, :class => "small-button" %></span>
  <% if @album.locations.length > 0 %>
    <% unless params[:location] == "true" %>
      <span><%= link_to "Show Location", query(:location => true),  :class => "small-button", :id => "toggle-location-button" %></span>
    <% else %>
      <span><%= link_to "Hide Location", query(:location => false), :class => "small-button", :id => "toggle-location-button" %></span>
    <% end %>
  <% end %>
</div>

<div id="albums-container">
  <% if @album.locations.length > 0 %>
    <div id="albums-map" <%= params[:location] == "true" ? "" : "class='hidden'" %>>
      <% @locations = @album.locations %>
      <%= render :partial => "locations/map" %>
    </div>
  <% end %>

  <div id="albums-thumbnails"<%= params[:view] == "list" ? "style='display:none;'" : "" %>>
    <% @album.photos.each do |photo| %>
      <div class="image">
        <%= link_to image_tag(photo.thumb, :size => "150x150"), photo_path(photo), :title => photo.title %>
      </div>
    <% end %>
  </div>

  <div id="albums-listing"<%= params[:view] == "list" ? "" : "style='display:none';" %>>
    <table>
      <tbody>
        <% @album.photos.each do |photo| %>
          <tr>
            <td><%= link_to image_tag(photo.thumb, :size => "100x100"), photo_path(photo), :title => photo.title %></td>
            <td>
              <div class="album-short">
                <b><div><%= photo.title %></div></b><br />
                Updated <%= time_ago_in_words(photo.updated_at) %> ago.<br />
                <%= photo.description %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div style="clear: both;"></div>
</div>

<div class="left-offset"><%= render :partial => "pages/social" %></div>

app/views/feedback/_new.html.erb
<%= form_for @new_feedback do |f| %>
  <%= f.label :name, "Your Name" %><br />
  <%= f.text_field :name %><br />
  <br />
  <%= f.label :email, "Email Address" %><br />
  <%= f.text_field :email %><br />
  <br />
  <%= f.label :can_contact, "May we contact you?" %>
  <%= f.check_box :can_contact %><br />
  <br />
  <%= f.label :person, "Are you a..." %><br />
  <%= f.select :person, Feedback.person_categories %><br />
  <%= f.hidden_field :browser, :id => "feedback-browser" %>
  <%= f.hidden_field :os, :id => "feedback-os" %>
  <%= f.hidden_field :browser_width, :id => "feedback-width" %>
  <%= f.hidden_field :browser_height, :id => "feedback-height" %>
  <%= f.label :content, "Feedback..." %><br />
  <%= f.text_area :content %>

  <br />
  <%= f.submit "Send Feedback" %>
  <br />
  <p>
  All fields are optional.  With your permission, a team member may contact you only about your feedback at the given email address.  By filling out this field we collect information about your current browser, operating system, window resolution and IP address.
  </p>
<% end %>

app/views/menus/_individual.html.erb
<li>
  <% if @menu.pages.length == 1 %>
    <%= link_to @menu.title, page_path(@menu.pages.first) %>
  <% elsif @menu.pages.length > 1 %>
    <span><%= link_to @menu.title, menu_path(@menu) %></span>
    <ul class="sub-menu">
      <% @menu.items.each do |page| %>
        <li><%= sub_menu_link(page) %></li>
      <% end %>
    </ul>
  <% end %>
</li>

app/views/menus/_menu.html.erb
<nav>
<ul id="main-menu">
  <li><%= link_to "Home", Page.home %></li>
  <% Menu.ordered.each do |menu| %>
    <% @menu = menu %>
    <%= render :partial => "menus/individual" %>
  <% end %>
</ul>
</nav>

<br />

<%= link_to image_tag(image_path("frc_logo.png")), "http://usfirst.org", :target => "_blank", :class => "left-offset", :id => "first-logo" %>

app/views/menus/_twitter.html.erb
<div id="twitter-feed">
</div>

app/views/menus/show.html.erb
<%= content_for :title, @menu.title %>

<ul id="sub-menu-page">
  <% @menu.pages.each do |page| %>
    <li><%= link_to page.title, page_path(page) %></li>
  <% end %>
</ul>

<%= link_to "MMRambotics Sitemap", sitemap_path %>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

app/views/photos/show.html.erb
<% content_for :title, @photo.title %>

<div id="albums-header">
  <span id="album-header-info"><%= @photo.title %></span>
  <span><%= link_to "Album [#{@photo.album.title}]", album_path(@photo.album), :class => "small-button" %></span>
  <% if @photo.album.photos.length > 1 %>
    <span><%= link_to "Next", photo_path(@photo.next), :class => "small-button", :id => "next-photo" %></span>
    <span><%= link_to "Prev", photo_path(@photo.prev), :class => "small-button", :id => "prev-photo" %></span>
    <% if @photo.locations.length > 0 %>
      <% unless params[:location] == "true" %>
        <span><%= link_to "Show Location", query(:location => true),  :class => "small-button", :id => "toggle-location-button" %></span>
      <% else %>
        <span><%= link_to "Hide Location", query(:location => false), :class => "small-button", :id => "toggle-location-button" %></span>
      <% end %>
    <% end %>
  <% end %>
</div>

<% if @photo.locations.length > 0 %>
  <div id="albums-map" <%= params[:location] == "true" ? "" : "class='hidden'" %>>
    <% @locations = @photo.locations %>
    <%= render :partial => "locations/map" %>
  </div>
<% end %>

<div id="image">
  <div id="image-box">
    <%= link_to image_tag(@photo.image, :width => "670"), @photo.image.url, :title => @photo.title, :target => "_blank" %>
  </div>
  <div id="image-data">
    <%= @photo.description %>
  </div>
</div>

<div class="left-offset"><%= render :partial => "pages/social" %></div>

app/views/photos/show.js.erb
$("#header h2").text("<%= @photo.title %>");
$("#next-photo").attr("href", "<%= photo_path(@photo.next) %>");
$("#prev-photo").attr("href", "<%= photo_path(@photo.prev) %>");
$("#image-box img").attr("src", "<%= @photo.image.url %>");
$("#image-box a").attr("title", "<%= @photo.title %>");
$("#image-box a").attr("href", "<%= @photo.image.url %>");
$("#image-data").html("<%=j @photo.description %>")
document.title = "<%= @photo.title %> | MMRambotics FRC #2200";
if (window.history.pushState)
  window.history.pushState({}, "<%= @photo.title %> | MMRambotics FRC #2200", "<%= photo_path(@photo) %>");